on:
  push:
    branches:
      - 'main'
      - 'develop'
    tags:
      - "v*.*"

name: build & publish

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - stable-i686
        - stable-x86_64
        - stable-armv7
        - stable-arm64
        include:
        - build: stable-i686
          os: ubuntu-22.04
          target: i686-unknown-linux-gnu
        - build: stable-x86_64
          os: ubuntu-22.04
          target: x86_64-unknown-linux-gnu
        - build: stable-armv7
          os: ubuntu-22.04
          target: armv7-unknown-linux-gnueabihf
          strip: arm-linux-gnueabihf-strip
        - build: stable-arm64
          os: ubuntu-22.04
          target: aarch64-unknown-linux-gnu
          strip: aarch64-linux-gnu-strip
    steps:
      - uses: actions/checkout@v6
        name: Check out git
      - name: Install dependencies
        if: contains(matrix.target, 'linux') 
        run: |
          sudo apt-get install -y pkg-config libssl-dev clang openssl perl
      - uses: dtolnay/rust-toolchain@master
        name: Set up Rust
        with:
          toolchain: stable
      - name: Set up Cross
        if: matrix.target != ''
        run: |
          cargo install cross
          echo "CARGO=cross" >> $GITHUB_ENV
          echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
          echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV
          echo "OPENSSL_DIR"=/usr/local/ssl >> $GITHUB_ENV
      - name: Cargo build
        run: |
          cross build -r --workspace ${{ env.TARGET_FLAGS }}
      - name: Strip release binary (x86)
        if: contains(matrix.target, 'linux') && !contains(matrix.build, 'arm')
        run: strip "target/${{ matrix.target }}/release/unattended-setups"
      - name: Strip release binary (arm)
        if: contains(matrix.target, 'linux') && contains(matrix.build, 'arm') && matrix.strip != ''
        run: |
          docker run --rm -v \
            "$PWD/target:/target:Z" \
            rustembedded/cross:${{ matrix.target }} \
            ${{ matrix.strip }} \
            /target/${{ matrix.target }}/release/unattended-setups
      - name: Add files to archive
        run: | 
          tar -C ./target/${{ matrix.target }}/release -czvf unattended-setups-${{ matrix.target }}.tar.gz unattended-setups
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: unattended-setups-${{ matrix.build }}
          path: unattended-setups-${{ matrix.target }}.tar.gz
          retention-days: 7
  release-deploy:
    name: deploy release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v6
      name: download artifacts
    - name: Display artifacts
      run: ls -R
    - uses: softprops/action-gh-release@v2
      name: publish prerelease
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: "${{ github.head_ref || github.ref_name }}"
        prerelease: true
        name: "Development build: ${{ github.head_ref || github.ref_name }}"
        files: |
          ./*/*.tar.gz
